### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by sckott** [ropensci/styleguide#1]
Should we rename this from `styleguide` to something like `guide`?  Basically, it makes sense to have this be more than just style per se (syntax spacing, indentation, etc.), so maybe rename?

@ropensci/owners

**Comment by jennybc** [comment]
package guidelines?

**Comment by karthik** [comment]
@sckott Agreed. Maybe `packaging_guide`?

**Comment by sckott** [comment]
cool, `packaging_guide`
