### ISSUE TITLE
NEWS & Relases

### ISSUE THREAD

**Issue by sckott** [ropensci/styleguide#11]
I'd suggest that it be mandatory that pkg authors use a NEWS or NEWS.md file, **AND** that on each CRAN release relavant news bits are put into a tagged release on the Releases tab for their repo. 

sound good? 

@ropensci/leadership

**Comment by cboettig** [comment]
:+1:

**Comment by karthik** [comment]
I also like Dean's idea of including date on the each release. So that way one can quickly know when the last update was.

**Comment by sckott** [comment]
sounds good

**Comment by karthik** [comment]
Maybe a constructive way forward is that we include a sample NEWS.md here and point out things that people should strive to include. Key information, how to succinctly describe changes, what level to summarize, etc.

**Comment by sckott** [comment]
sounds good.

**Comment by sckott** [comment]
^^ thoughts

**Comment by karthik** [comment]
I like it. One other idea, is to do an annotated version (using photoshop) for the README. I can do it, but not till later in the week. Here is an example from an upcoming blog post of mine: 

![](http://inundata.org/images/joss.png)

We'd show people that things like (#18) mean issue #18 in their repo. etc.

**Comment by daattali** [comment]
I'm glad to know someone thought my idea to include the data in news was good -- on Twitter I received a lot of pushback on that :)

What are your thoughts on only suggesting to use `NEWS.md` and not `NEWS`?  From what I can tell, `NEWS.md` seems to be the convention, it's accepted by CRAN, it's what Hadley recommends in his book, and it just seems to fit better with the general idea that all human-readable meta-files are markdown

**Comment by maelle** [comment]
Closing this before archiving the repo since development of guidelines moved to https://github.com/ropensci/dev_guide (and after gathering the ideas that haven't implemented yet 👼 )
