### ISSUE TITLE
More CI guidance

### ISSUE THREAD

**Issue by sckott** [ropensci/styleguide#14]
we have https://github.com/ropensci/packaging_guide#ci but it should strongly suggest using the new travis setup with package caching, etc. and we can even put an example travis file in (and appveyor too if we think that's important )

**Comment by carlganz** [comment]
Agreed. Should also mention whether people should use Travis to test on Linux _and_ Mac, and if they should use AppVeyor for Windows.

**Comment by sckott** [comment]
thanks @carlganz we've moved the packaging guide to the onboarding repo https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#ci - looks like we didn't incorporate this yet though

**Comment by maelle** [comment]
Closing this before archiving the repo since development of guidelines moved to https://github.com/ropensci/dev_guide

It has more CI guidance https://ropensci.github.io/dev_guide/ci.html including a list of reasons why to use Appveyor for Windows.
