### ISSUE TITLE
Avoid package startup messages?

### ISSUE THREAD

**Issue by richfitz** [ropensci/styleguide#15]
Perhaps we already discussed this, or it may be too pedantic, but any chance we can recommend **not** having package startup messages.  I don't know how many (if any) of our packages do, but they're fairly common and annoying to have to suppress.

**Comment by jennybc** [comment]
Not sure which package is bugging you, but for me it's `dplyr`. And yet I can't truly claim those startup messages (about masking functions) should, in general, be suppressed.

So maybe this needs to be a discussion about what merits a startup message and what does not. Anything that does .... probably ties back to a discussion of whether you can eliminate the message-worthy behaviour and have a less surprising package. With no startup messages.

**Comment by richfitz** [comment]
Things like

```
This is vegan 2.4-0
```

bug me.  Perhaps they shouldn't?  But you see packages where there's a great big screed of text exhorting you cite them and referencing papers and the like.

Function masking is another thing, and definitely worth avoiding.

**Comment by jennybc** [comment]
OK I agree the announcement of version and "where to send your citations" is not cool.

**Comment by maelle** [comment]
Added some sort of guidance digesting the (interesting, thanks) conversation above, feel free to comment in the corresponding repo.

Closing this before archiving the repo since development of guidelines moved to https://github.com/ropensci/dev_guide
