### ISSUE TITLE
Clarify: does rOpenSci logo have to go in the README before submission or only after package is accepted?

### ISSUE THREAD

**Issue by daattali** [ropensci/styleguide#19]
The reviewer instructions say that one of the things we should look for is whether the ropensci logo is included in the README.  However, it's a bit unclear to the package author when they should add the logo.  If it should be done before the submission, then it should be mentioned to the authors.  If it should be done after submission, then it shouldn't be something that the reviewer looks for.

This issue confused me when I did a package review previously, and @ttimbers also seems to be confused by the exact same issue https://github.com/ropensci/onboarding/issues/56#issuecomment-234017233

**Comment by sckott** [comment]
@noamross I think we'd only want it added after package is approved, yes?  b/c if it's not approved, then there's no reason to add it

**Comment by noamross** [comment]
Agreed.  It should be added after approval, preferably before transferring
the repository.

**Comment by sckott** [comment]
yeah, before transfer

**Comment by maelle** [comment]
Added "before transfer" to the guide, the rest had already been clarified.

Closing this before archiving the repo since development of guidelines moved to https://github.com/ropensci/dev_guide
