### ISSUE TITLE
Information about priority

### ISSUE THREAD

**Issue by richfitz** [ropensci/styleguide#2]
Style guides have a lot of information, usually.  If you're coming from coding without any guidelines it can seem very daunting.  So it might be nice to offer some guidance as to which order to pay attention to things.

For example 
- "no underscores in package names" will prevent a package from being installed, so that's top priority. :bangbang:  Things like examples, vignettes, etc that get close to policy might also go here.
- "function/variable naming in `snake_case`" is highly visible to users so might be "good to have" :exclamation:
- Indenting, spaces around operators, etc are purely stylistic so might fall into a "nice to have" :+1:

Ordering the suggestions within categories and moving categories that have the most important things up the list will make it easier for newcomers to adapt without overwhelming them.

**Comment by sckott** [comment]
Good idea Rich, prioritizing seems like a good way to make sure people are seeing the most important things first.
