### ISSUE TITLE
Recommendations for or against packrat

### ISSUE THREAD

**Issue by jsta** [ropensci/styleguide#20]
I am reviewing a package that makes use of `packrat`. Do we want to give some guidance on its use in the guide?

**Comment by cboettig** [comment]
Might be reasonable for a 'compendium', but seems like a strange choice for a generic user-facing package like those that go through on-boarding.  Can you give us more context or any explanation for this decision from the authors?

If this isn't a common thing I'm not sure it's worth mentioning explicitly in the guide.

**Comment by jsta** [comment]
I agree. It seems like including `packrat` was more of experiment in this case. In the end, it might cause confusion for end-users.
