### ISSUE TITLE
should we move all discussion here to onboarding?

### ISSUE THREAD

**Issue by sckott** [ropensci/styleguide#21]
given that we have the packaging guide in onboarding https://github.com/ropensci/onboarding/blob/master/packaging_guide.md

@maelle @noamross @karthik

**Comment by maelle** [comment]
or to the repo we said we might create?

**Comment by noamross** [comment]
Yes to what @maelle said. We should actually delete the content of this repo and leave a simple README saying that that everything is on onboarding.  I think a link or two in the onboarding repo still mistakenly points here.

**Comment by noamross** [comment]
Oh hey: https://github.com/ropensci/packaging_guide/pull/17/files

**Comment by karthik** [comment]
>  We should actually delete the content of this repo and leave a simple README saying that that everything is on onboarding.

Agreed

**Comment by sckott** [comment]
nice, looks like we should merge that PR
