### ISSUE TITLE
Vignette, README

### ISSUE THREAD

**Issue by jennybc** [ropensci/styleguide#4]
Include strong encouragement or requirement to have a vignette and README.md that shows basics usage?

(BTW is it a foregone conclusion that the packages these guidelines apply to will be on GitHub?)

**Comment by sckott** [comment]
> (BTW is it a foregone conclusion that the packages these guidelines apply to will be on GitHub?)

yes, we haven't accepted any pkgs under our umbrella that aren't on GitHub, seems okay to set that as a rule

Agree, i think README and at least 1 vignette are required.

**Comment by lmullen** [comment]
Would it be worthwhile to include the Markdown snippet for the rOpenSci README footer image?

**Comment by sckott** [comment]
oh yeah, good idea @lmullen

**Comment by sckott** [comment]
okay, added bits on readme and vignettes, anything to change? @jennybc @lmullen

**Comment by lmullen** [comment]
Looks good to me.

**Comment by jennybc** [comment]
I suggest you mention the idea of creating `README.md` from `README.Rmd`. @hadley added `use_readme_rmd()` to `devtools`, as a nice helper function. This encourages people to put working code in the `README`, sort of a mini-vignette. This is quite important since compiled vignettes are hard to access for GitHub packages one has not installed yet.

**Comment by sckott** [comment]
:+1: sounds good

will do

**Comment by lmullen** [comment]
Is there a best practice about whether or not to commit the compiled vignette in `inst/doc`? I've been putting the compiled vignettes on my website so that I can link to them from the `README`, but this is not the easiest thing to keep in sync.

**Comment by hadley** [comment]
I don't think you should ever put in `inst/doc` (because it interferes with R CMD build/check), but it's reasonable to include built sources in `vignettes/`. The dev version of roxygen adds a new roclet to automatically re-build the vignettes when they change.

**Comment by sckott** [comment]
i think this is done
