### ISSUE TITLE
avoid pedantic / unjustified preferences

### ISSUE THREAD

**Issue by cboettig** [ropensci/styleguide#5]
The packaging guide is a bit too pedantic in places, without providing more reasons for certain preferences.  e.g.

> For parinsg XML, use xml2 instead of XML

Okay, there are definite advantages to some of the parsing behavior in xml2; but if a package is serializing as well as parsing in XML, it probably doesn't make sense to use `xml2` for parsing and `XML` for serializing.  `xml2` is not on CRAN and is still in active development, and there are a lot fewer examples in the wild of how to use it; all of which might be reasons a developer would prefer XML.  

I think rOpenSci can play a great role here in helping developers understand the advantages of some of these new tools over existing packages (`jsonlite` vs `RJSON`), but I don't think we should ever do so without context.  I think that runs the risk of devaluing our perspective.

I think this issue arises beyond just the tools section recommending packages.  e.g. there's a lot of style guides out there.  Hadley gives a very nice introduction to his style guide, acknowledging the existence of other style guides and explaining his reasons.  I think it's important we do likewise -- acknowledge where a choice is arbitrary but we state a preference just to keep things consistent where possible, and acknowledge where a choice has really objective performance differences etc.

**Comment by sckott** [comment]
@cboettig Tried to address this, anything else you see that needs changing?

**Comment by karthik** [comment]
I also agree and perhaps this is a separate issue, but I think it's too verbose. Scott did a great job compiling this, but we also don't want to replicate too much from Advanced R or R packages given that both books are openly available and have been edited for clarity. 

How about we boil this down to no more than a printed page, the move the other material into separate pages linked from the main?

**Comment by karthik** [comment]
ok, @cboettig @sckott @richfitz @jennybc 
Thoughts on the concise version? See `edits` branch.

**Comment by karthik** [comment]
I removed various verbose bits. Like there doesn't need to be a long explanation about checking names on CRAN (that automatically results in a note during onboarding)

Shorter section on sematic versioning (Hadley covered in in more detail in R-pkgs)

Deleted OO and APIs because that is more of a development issue than a style guide. Neither were detailed enough to be useful.

**Comment by cboettig** [comment]
@karthik Looks great, really like the nice concise version.  Maybe the
semantic versioning can be even shorter? (and link directly to the section
in Hadley's book on this?)

In the same spirit as these edits, it might be helpful to link some other
sections directly to the relevant bits of Hadley's books.  We already do a
good job of this for about half of the sections we list (which is awesome
since I don't need to remember whether it's in advanced R or packaging
first and then go searching the contents).

**Comment by sckott** [comment]
if you really want to just point people to hadley's books, then why have this guide at all?

**Comment by karthik** [comment]
> if you really want to just point people to hadley's books, then why have this guide at all?

To list things that we want to see in packages submitted to us. It makes little sense to rewrite sections from his book again. We suggest DRYing out code, why not these explanations as well?

**Comment by cboettig** [comment]
Yup, we suggest things that aren't in among Hadley's recommendations, and
this guide also highlights the most important stuff.  If we didn't have a
guide and just linked his I think we'd still wind up telling people to use
semantic version numbers, and CI, and having to catch calls to "print()"
when someone should have used message() etc.

**Comment by karthik** [comment]
Few more edits to `edits` branch. If anyone else wants to clean it up and improve, we can do a PR.

**Comment by maelle** [comment]
Closing this before archiving the repo since development of guidelines moved to https://github.com/ropensci/dev_guide.
