### ISSUE TITLE
fix line on when to use "Enhances" vs "Suggests"

### ISSUE THREAD

**Issue by cboettig** [ropensci/styleguide#6]
We say to use "Enhances" for packages used in examples, but I think this isn't correct and should be "Suggests".  [From Writing R Extensions](http://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies)

> Finally, the ‘Enhances’ field lists packages “enhanced” by the package at hand, e.g., by providing methods for classes from these packages, or ways to handle objects from these packages (so several packages have ‘Enhances: chron’ because they can handle datetime objects from chron even though they prefer R’s native datetime functions). Version requirements can be specified, but are currently not used. Such packages cannot be required to check the package: any tests which use them must be conditional on the presence of the package. (If your tests use e.g. a dataset from another package it should be in ‘Suggests’ and not ‘Enhances’.)

**Comment by maelle** [comment]
Better late than never :joy: Thanks @cboettig!

For info now development of guidelines moved to https://github.com/ropensci/dev_guide.
